!classDefinition: #PEPE category: #pepera!
DenotativeObject subclass: #PEPE
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'pepera'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'PEPE class' category: #pepera!
PEPE class
	instanceVariableNames: ''!

!PEPE class methodsFor: 'as yet unclassified' stamp: 'asd 8/27/2018 20:55:46'!
mensaje
	^ 'bye'! !
